- hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone yay
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "/opt/yay"
        update: true
        become: true

    - name: Change file permissions of yay folder
      ansible.builtin.file:
        path: /opt/yay
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        become: true

    - name: Build and install yay
      command:
        chdir: "/opt/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay

    - name: Install my packages from AUR using yay
      community.general.pacman:
        name: 
          - protonvpn
          - hyprland
          - waybar-hyprland
          - wlogout
        state: present
        executable: yay
        extra_args: --builddir /var/cache/yay

