- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install all of my packages through pacman
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - wget
          - feh
          - rsync
          - git
          - keepassxc
          - qt5ct
          - dunst
          - cmus
          - ranger
          - unzip
          - syncthing
          - network-manager-gnome
          - sddm
          - gnome-keyring
          - papirus-icon-theme
          - nautilus
          - foot
          - rofi
          - breeze
          - swaybg
          - swayidle
          - zsh
          - pavucontrol
          - apparmor
          - cifs-utils
          - sway
          - waybar
        state: present

    - name: Enable syncthing on boot
      ansible.builtin.command: systemctl enable syncthing@{{ lookup('env', 'SUDO_USER') }}

    - name: Enable sddm on boot
      ansible.builtin.command: systemctl enable sddm

    - name: Enable apparmor on boot
      ansible.builtin.command: systemctl enable apparmor

