- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install all of my packages through pacman
      ansible.builtin.pacman:
        name:
          - vim
          - curl
          - wget
          - feh
          - firefox
          - rsync
          - git
          - qt5ct
          - mako
          - cmus
          - ranger
          - unzip
          - network-manager-applet
          - sddm
          - gnome-keyring
          - papirus-icon-theme
          - nautilus
          - foot
          - rofi
          - breeze
          - swaybg
          - swayidle
          - swaylock
          - zsh
          - pavucontrol
          - apparmor
          - cifs-utils
          - sway
          - waybar
          - ncspot
        state: present

    - name: Enable sddm on boot
      ansible.builtin.command: systemctl enable sddm

    - name: Enable apparmor on boot
      ansible.builtin.command: systemctl enable apparmor

