- hosts: localhost
  gather_facts: false
  tasks:
    - name: Enable firejail
      ansible.builtin.command: firecfg
    
    - name: Install hardned malloc aur
      community.general.pacman:
        name: hardened_malloc
        state: present
        executable: yay
        extra_args: --builddir /var/cache/yay

    - name: Enable hardened malloc on the entire system
      ansible.builtin.lineinfile:
        path: /etc/ld.so.preload
        line: /usr/lib/libhardened_malloc.so
        create: yes

    - name: Change vm.max_map_count to accommodate the very large number of guard pages created by hardened_malloc
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/hardened_malloc.conf
        line: vm.max_map_count = 1048576
        create: yes

    - name: Enforce a delay after a failed login attempt
      ansible.builtin.lineinfile:
        path: /etc/pam.d/system-login
        line: auth optional pam_faildelay.so delay=4000000
    
    - name: Check if grub cmdline is edited for apparmor
      lineinfile:
        backup: true
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".*lsm=landlock,lockdown,yama,integrity,apparmor,bpf lockdown=confidentiality'
        state: absent
      check_mode: true
      register: grub_cmdline_check
      changed_when: false
    
    - name: add change to grub cmdline for apparmor
      lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
        line: '\1 lsm=landlock,lockdown,yama,integrity,apparmor,bpf lockdown=confidentiality"'
      when: grub_cmdline_check.found == 0

    - name: Rebuild kernel after changing settings in /etc/default/grub
      ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
      when: grub_cmdline_check.found == 0

    - name: Create secure boot keys
      ansible-builtin.command: sbctl create-keys
    
    - name: Enroll newly created keys
      ansible-builtin.command: sbctl enroll-keys

    - name: Sign BOOTX64.efi
      ansible-builtin.command: sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI

    - name: Sign core.efi
      ansible-builtin.command: sbctl sign -s /boot/grub/x86_64-efi/core.efi

    - name: Sign grub.efi
      ansible-builtin.command: sbctl sign -s /boot/grub/x86_64-efi/grub.efi

    - name: Sign vmlinuz-linux-hardened
      ansible-builtin.command: sbctl sign -s /boot/vmlinuz-linux-hardened
    
    - name: Verify keys
      ansible-builtin.command: sbctl verify

    - name: Enable newer AMDGPU for Southern Islands gpu
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/amdgpu.conf
        line: options amdgpu si_support=1
    
    - name: Disable radeon driver
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/radeon.conf
        line: options radeon si_support=0

    - name: Rebuild kernel with new changes
      ansible-builtin.command: mkinitcpio -p linux-hardened

    - name: Hide other users processes (can cause issues)
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: proc	/proc	proc	nosuid,nodev,noexec,hidepid=2,gid=proc	0	0
